#encoding=utf8

RTM_SDK_VERSION = '2.1.1'
RTM_INTERFACE_VERSION = '2.2.0'

class RTMServerConfig:
    GLOBAL_CONNECT_TIMEOUT_SECONDS = 30
    GLOBAL_QUEST_TIMEOUT_SECONDS = 30
    FILE_GATE_CLIENT_HOLDING_SECONDS = 150
